#!/usr/bin/env bash

# ==============================================================================
# Script: 08_targeted_deeptools_plot_profile.sh
# Package: Transposable element analysis scripts
#
# Purpose:
#   Cleaned author-generated scripts for TE catalog construction, TE differential-expression annotation, TE-gene overlap, IAP summaries, methylation metaprofiles, and heatmaps.
#
# Notes:
#   - Paths are supplied by command-line arguments where possible.
#   - Standard external tools/packages are described in the Methods.
#   - This script documents the manuscript-facing analysis logic.
# ==============================================================================

# 08_targeted_deeptools_plot_profile.sh
#
# Replot selected TE-family methylation metaprofiles from existing deepTools
# computeMatrix output using fixed y-axis ranges.
#
# This script is intended for presentation/figure plotting after matrices have
# already been generated by 05_make_te_methyl_profiles.sh.
#

# Usage:
#   bash 08_targeted_deeptools_plot_profile.sh \
#     --profile-dir /path/to/TE_methyl_profiles \
#     --ranges ranges.tsv
#
# ranges.tsv format:
#   family    yMin    yMax
#   IAPEZI    40      60
#   RLTR13B3  25      75
#
# Expected matrices:
#   <profile-dir>/matrices/<family>_<timepoint>h.mat.gz

set -euo pipefail

usage() {
  grep '^#' "$0" | sed 's/^# \{0,1\}//'
  exit 1
}

PROFILE_DIR=""
RANGES_TSV=""
TIMES="1 6 24"
AVERAGE_TYPE="mean"
MAKE_JPG=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --profile-dir) PROFILE_DIR="$2"; shift 2;;
    --ranges) RANGES_TSV="$2"; shift 2;;
    --times) TIMES="$2"; shift 2;;
    --average-type) AVERAGE_TYPE="$2"; shift 2;;
    --make-jpg) MAKE_JPG="$2"; shift 2;;
    -h|--help) usage;;
    *) echo "ERROR: unknown argument: $1" >&2; usage;;
  esac
done

[[ -d "$PROFILE_DIR" ]] || { echo "ERROR: --profile-dir not found" >&2; exit 1; }
[[ -f "$RANGES_TSV" ]] || { echo "ERROR: --ranges file not found" >&2; exit 1; }

command -v plotProfile >/dev/null || { echo "ERROR: plotProfile not found" >&2; exit 1; }

read -r -a TIME_ARRAY <<< "$TIMES"

# Skip header if present. Accept tab- or space-delimited input.
awk 'BEGIN{FS="[ \t]+"; OFS="\t"} NR==1 && tolower($1)=="family"{next} NF>=3{print $1,$2,$3}' "$RANGES_TSV" |
while IFS=$'\t' read -r FAM YMIN YMAX; do
  [[ -z "$FAM" ]] && continue

  echo "[replot] $FAM y=($YMIN, $YMAX)"
  PLOT_DIR_FAM="$PROFILE_DIR/plots/$FAM"
  mkdir -p "$PLOT_DIR_FAM"

  for TP in "${TIME_ARRAY[@]}"; do
    MAT="$PROFILE_DIR/matrices/${FAM}_${TP}h.mat.gz"

    if [[ ! -f "$MAT" ]]; then
      echo "  [skip] ${TP}h: matrix not found -> $MAT"
      continue
    fi

    PDF="$PLOT_DIR_FAM/${FAM}_${TP}h_profile.pdf"
    PNG="$PLOT_DIR_FAM/${FAM}_${TP}h_profile.png"
    JPG="$PLOT_DIR_FAM/${FAM}_${TP}h_profile.jpg"
    TSV="$PROFILE_DIR/matrices/${FAM}_${TP}h_profile.tsv"

    plotProfile -m "$MAT" \
      --samplesLabel "${TP}h KCl" "${TP}h Mannitol" \
      --plotTitle "${FAM} - ${TP}h (KCl vs Mannitol)" \
      --yAxisLabel "%mCG" \
      --perGroup \
      --averageType "$AVERAGE_TYPE" \
      --regionsLabel "" \
      --numPlotsPerRow 1 \
      --plotFileFormat pdf \
      --yMin "$YMIN" \
      --yMax "$YMAX" \
      --outFileName "$PDF" \
      --outFileNameData "$TSV"

    plotProfile -m "$MAT" \
      --samplesLabel "${TP}h KCl" "${TP}h Mannitol" \
      --yAxisLabel "%mCG" \
      --perGroup \
      --averageType "$AVERAGE_TYPE" \
      --regionsLabel "" \
      --numPlotsPerRow 1 \
      --plotFileFormat png \
      --yMin "$YMIN" \
      --yMax "$YMAX" \
      --outFileName "$PNG"

    if [[ "$MAKE_JPG" -eq 1 ]] && command -v convert >/dev/null 2>&1; then
      convert "$PNG" "$JPG" || true
    fi
  done
done

echo "[done] Replotted selected TE families with fixed y-axis limits."
